# Generated by Django 5.1.6 on 2025-02-14 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_testing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название темы')),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Темы',
            },
        ),
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Ответ', 'verbose_name_plural': 'Ответы'},
        ),
        migrations.AlterModelOptions(
            name='direction',
            options={'verbose_name': 'Направление', 'verbose_name_plural': 'Направления'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterModelOptions(
            name='testresult',
            options={'verbose_name': 'Результат теста', 'verbose_name_plural': 'Результаты тестов'},
        ),
        migrations.AlterField(
            model_name='answer',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='Правильный ответ'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='app_testing.question', verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.CharField(max_length=255, verbose_name='Текст ответа'),
        ),
        migrations.AlterField(
            model_name='direction',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название направления'),
        ),
        migrations.AlterField(
            model_name='question',
            name='direction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='app_testing.direction', verbose_name='Направление'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(verbose_name='Текст вопроса'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='correct_answers',
            field=models.IntegerField(verbose_name='Правильные ответы'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата прохождения'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='direction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_testing.direction', verbose_name='Направление'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='surname',
            field=models.CharField(max_length=255, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='total_questions',
            field=models.IntegerField(verbose_name='Всего вопросов'),
        ),
        migrations.AddField(
            model_name='direction',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='directions', to='app_testing.theme', verbose_name='Тема'),
        ),
        migrations.AddField(
            model_name='question',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='app_testing.theme', verbose_name='Тема'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_testing.theme', verbose_name='Тема'),
        ),
    ]
