# Generated by Django 5.1.6 on 2025-02-14 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_testing', '0002_theme_alter_answer_options_alter_direction_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direction',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directions', to='app_testing.theme', verbose_name='Тема'),
        ),
    ]
