# Generated by Django 5.1.6 on 2025-02-14 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_testing', '0003_alter_direction_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direction',
            name='theme',
        ),
        migrations.RemoveField(
            model_name='question',
            name='theme',
        ),
        migrations.AddField(
            model_name='direction',
            name='themes',
            field=models.ManyToManyField(related_name='directions', to='app_testing.theme', verbose_name='Темы'),
        ),
        migrations.AddField(
            model_name='question',
            name='themes',
            field=models.ManyToManyField(related_name='questions', to='app_testing.theme', verbose_name='Темы'),
        ),
    ]
